const projects = {
  1: {
    important: false,
    url: 'portfolio.kaplan.edu',
    screens: [
      '/static/img/projects/kaplan-portfolio/01-phone.jpg',
      '/static/img/projects/kaplan-portfolio/01-tablet.jpg',
      '/static/img/projects/kaplan-portfolio/01.jpg',
    ],
    pictureHome: '/static/img/projects/kaplan-portfolio/thumb.jpg',
    name: 'Kaplan Portfolio Assessment',
    company: 'Kaplan University',
    project: 'Portfolio Assessment',
    roles: [
      'Ideation',
      'UX Design',
      'Front-end Developemnt',
    ],
    body: 'WebApp for Kaplan University, to help potencial students get college credits for whether user you’ve been working for years, served in the military, or spent time volunteering, showcasing your knowledge through our credit-for-work experience courses could save you thousands of dollars and help you finish your Kaplan University undergraduate degree faster.',
    released: 'November 2013',
    colors: [
      '#232a4d',
      '#434b68',
      '#0198ce',
      '#e0e0e0',
      '#333333',
    ],
    font: {
      face: 'Helvetica Neue',
      family: '"HelveticaNeue-UltraLight", "Helvetica Neue UltraLight", "Helvetica Neue", Helvetica, sans-serif',
      weight: 100,
      local: true,
      url: '',
    },
    stack: {
      1: {
        title: 'SketchApp',
        icon: 'icon-sketch',
      },
      2: {
        title: 'CreativeCloud',
        icon: 'icon-adobe',
      },
      3: {
        title: 'CSS',
        icon: 'icon-css',
      },
      4: {
        title: 'HTML5 Video',
        icon: 'icon-html',
      },
      5: {
        title: 'jQuery',
        icon: 'icon-jquery',
      },
      6: {
        title: 'Git',
        icon: 'icon-git',
      },
      7: {
        title: 'Angular',
        icon: 'icon-angular',
      },
      8: {
        title: 'Gulp',
        icon: 'icon-gulp',
      },
    },
  },
  2: {
    important: true,
    url: 'private',
    screens: [
      '/static/img/projects/bhi/bhi-lecture-series1.jpg',
      '/static/img/projects/bhi/bhi-lecture-series2.jpg',
    ],
    pictureHome: '/static/img/projects/bhi/thumb.jpg',
    name: 'Brain an Owners Guide',
    company: 'Center for the Brain Health',
    project: 'Brain: an Owners Guide',
    roles: [
      'UX Design',
      'Front-end Developemnt',
    ],
    body: 'The Brain lecture series 2015 Center for the Brain Health annual series sell-out public lecture series, delivers groundbreaking brain health research straight from renowned leaders of the field',
    released: 'January 2015',
    colors: [
      '#202c38',
      '#384a5e',
      '#00b0ec',
      '#b0d041',
      '#f0752f',
      '#a1539e',
      '#FFFFFF',
    ],
    font: {
      face: 'Helvetica Neue',
      family: '"HelveticaNeue-UltraLight", "Helvetica Neue UltraLight", "Helvetica Neue", Helvetica, sans-serif',
      weight: 200,
      local: true,
      url: '',
    },
    stack: {
      2: {
        title: 'CreativeCloud',
        icon: 'icon-adobe',
      },
      3: {
        title: 'CSS',
        icon: 'icon-css',
      },
      4: {
        title: 'HTML5',
        icon: 'icon-html',
      },
      5: {
        title: 'jQuery',
        icon: 'icon-jquery',
      },
      6: {
        title: 'Git',
        icon: 'icon-git',
      },
    },
  },
  3: {
    important: false,
    url: 'visionaryvoices.kaplan.edu',
    screens: [
      '/static/img/projects/vv/home.jpg',
      '/static/img/projects/vv/categories.jpg',
      '/static/img/projects/vv/event.jpg',
      '/static/img/projects/vv/categories-ui.jpg',
      '/static/img/projects/vv/speakers.jpg',
      '/static/img/projects/vv/home-ipad-nav.jpg',
    ],
    pictureHome: '/static/img/projects/vv/thumb.jpg',
    name: 'Kaplan Visionary Voices',
    company: 'Kaplan Inc.',
    project: 'Visionary Voices',
    roles: [
      'UX Design',
      'Front-end Developemnt',
    ],
    body: 'Kaplan University presents Visionary Voices, a series of interviews that chronicle our goals in regards to adult education and continuing education throughout your life. Kaplan University offers online degree programs designed to expand the way you think and help you develop both personally and professionally. Students turn to us to develop their critical thinking skills, to challenge and prepare them for successful careers.',
    released: 'February 2014',
    colors: [
      '#2e2f33',
      '#444444',
      '#00a6da',
      '#dfdfdf',
      '#000000',
    ],
    font: {
      face: 'Open Sans',
      family: '"Open Sans", sans-serif',
      weight: 200,
      local: false,
      url: 'https://fonts.googleapis.com/css?family=Open+Sans:300',
    },
    stack: {
      1: {
        title: 'CreativeCloud',
        icon: 'icon-adobe',
      },
      2: {
        title: 'CSS',
        icon: 'icon-css',
      },
      3: {
        title: 'HTML5',
        icon: 'icon-html',
      },
      4: {
        title: 'jQuery',
        icon: 'icon-jquery',
      },
      5: {
        title: 'Git',
        icon: 'icon-git',
      },
    },
  },
  4: {
    important: false,
    url: 'redskins.kaplan.edu',
    screens: [
      '/static/img/projects/redskins/home1.jpg',
      '/static/img/projects/redskins/home2.jpg',
    ],
    pictureHome: '/static/img/projects/redskins/thumb.jpg',
    name: 'Kaplan Washington Redskins',
    company: 'Washington Redskins',
    project: 'Playbook for Success',
    roles: [
      'UX Design',
    ],
    body: 'Washington Redskins presents Playbook for Success, a series of interviews. Kaplan University, the exclusive higher education partner of The Washington Redskins, is giving you the chance to increase your draft ranking by going inside their playbook and having your strategies for success answered in a live, four-part speaker series.',
    released: 'February 2014',
    colors: [
      '#145f62',
      '#2caea6',
      '#ff4900',
      '#e5e5e5',
      '#FFFFFF',
      '#333333',
    ],
    font: {
      face: 'Open Sans',
      family: '"Open Sans", sans-serif',
      weight: 200,
      local: false,
      url: 'https://fonts.googleapis.com/css?family=Open+Sans:300',
    },
    stack: {
      1: {
        title: 'CreativeCloud',
        icon: 'icon-adobe',
      },
    },
  },
  5: {
    important: false,
    url: 'aarptek.aarp.org',
    screens: [
      '/static/img/projects/aarp/Home-02-phone.jpg',
      '/static/img/projects/aarp/Home-02-tablet.jpg',
      '/static/img/projects/aarp/Home-02.jpg',
    ],
    pictureHome: '/static/img/projects/aarp/thumb.jpg',
    name: 'AARP TEK',
    company: 'AARP',
    project: 'Technology Education Knowledge',
    roles: [
      'UX Design',
      'UI Design',
    ],
    body: 'POC for the re-design of AARP Technology Education Knowledge platform.',
    released: 'February 2014',
    colors: [
      '#414e56',
      '#ef1a1e',
      '#3598db',
      '#ebebeb',
      '#FFFFFF',
    ],
    font: {
      face: 'Open Sans',
      family: '"Open Sans", sans-serif',
      weight: 200,
      local: false,
      url: 'https://fonts.googleapis.com/css?family=Open+Sans:300',
    },
    stack: {
      1: {
        title: 'CreativeCloud',
        icon: 'icon-adobe',
      },
    },
  },
  6: {
    important: false,
    url: 'indigo.luc.edu',
    screens: [
      '/static/img/projects/luc/02-phone.jpg',
      '/static/img/projects/luc/02-desktop.jpg',
      '/static/img/projects/luc/01.jpg',
      '/static/img/projects/luc/03.jpg',
    ],
    pictureHome: '/static/img/projects/luc/thumb.jpg',
    name: 'Indigo Learning Platform',
    company: 'Loyola University Chicago',
    project: 'Loyola University Indigo',
    roles: [
      'UX Design',
      'UI Design',
    ],
    body: 'Re-design of Loyola University Chicago online education platform, Indigo Learning Platform',
    released: 'Novenber 2014',
    colors: [
      '#177bb9',
      '#a4044a',
      '#ebebeb',
      '#FFFFFF',
      '#333333',
    ],
    font: {
      face: 'Maven Pro',
      family: '"Maven Pro", sans-serif',
      weight: 200,
      local: false,
      url: 'https://fonts.googleapis.com/css?family=Maven+Pro',
    },
    stack: {
      1: {
        title: 'CreativeCloud',
        icon: 'icon-adobe',
      },
    },
  },
  7: {
    important: false,
    url: 'portfolio.kaplan.edu',
    screens: [
      '/static/img/projects/kaplan-portfolio/01-phone.jpg',
      '/static/img/projects/kaplan-portfolio/01-tablet.jpg',
      '/static/img/projects/kaplan-portfolio/01.jpg',
    ],
    pictureHome: '/static/img/projects/kaplan-portfolio/thumb.jpg',
    name: 'Kaplan Portfolio Assessment',
    company: 'Kaplan University',
    project: 'Portfolio Assessment',
    roles: [
      'Ideation',
      'UX Design',
      'Front-end Developemnt',
    ],
    body: 'WebApp for Kaplan University, to help potencial students get college credits for whether user you’ve been working for years, served in the military, or spent time volunteering, showcasing your knowledge through our credit-for-work experience courses could save you thousands of dollars and help you finish your Kaplan University undergraduate degree faster.',
    released: 'November 2013',
    colors: [
      '#232a4d',
      '#434b68',
      '#0198ce',
      '#e0e0e0',
      '#333333',
    ],
    font: {
      face: 'Helvetica Neue',
      family: '"HelveticaNeue-UltraLight", "Helvetica Neue UltraLight", "Helvetica Neue", Helvetica, sans-serif',
      weight: 100,
      local: true,
      url: '',
    },
    stack: {
      1: {
        title: 'SketchApp',
        icon: 'icon-sketch',
      },
      2: {
        title: 'CreativeCloud',
        icon: 'icon-adobe',
      },
      3: {
        title: 'CSS',
        icon: 'icon-css',
      },
      4: {
        title: 'HTML5 Video',
        icon: 'icon-html',
      },
      5: {
        title: 'jQuery',
        icon: 'icon-jquery',
      },
      6: {
        title: 'Git',
        icon: 'icon-git',
      },
      7: {
        title: 'Angular',
        icon: 'icon-angular',
      },
      8: {
        title: 'Gulp',
        icon: 'icon-gulp',
      },
    },
  },
  8: {
    _id: '596aa7a1b58714fbe56ec412',
    index: 4,
    isActive: true,
    important: false,
    picture: 'http://placehold.it/1300x400',
    pictureHome: 'http://placehold.it/500x500',
    name: 'id deserunt eu duis ea',
    company: 'Zenolux2',
    project: 'Adipisicing laborum proident tempor aliquip irure proident ullamco sit sint.',
    body: 'Cillum fugiat fugiat quis enim voluptate non reprehenderit exercitation ut magna culpa nostrud dolore sunt. In qui tempor quis tempor exercitation velit cillum incididunt aliquip pariatur anim et. Deserunt aliqua elit nulla id ullamco sit.\r\nReprehenderit occaecat deserunt id dolore magna officia Lorem tempor sunt proident cillum. Occaecat dolore nisi non sunt ad cillum irure culpa. Commodo est reprehenderit anim exercitation laboris esse. In ipsum nulla aliqua sit duis Lorem est. Irure ullamco do duis adipisicing consequat cillum cillum aliquip. Velit esse id fugiat aliquip commodo labore. Sint incididunt amet Lorem id.\r\nId nisi non ipsum commodo do esse occaecat. Dolore incididunt est amet sit. Id aliquip dolor nisi exercitation enim ut in incididunt consectetur incididunt ad ea. Occaecat irure velit culpa mollit ullamco consectetur officia. Elit consectetur adipisicing sint occaecat aliqua. Incididunt ea sint consequat dolor laboris tempor labore.\r\n',
    released: '2014-11-12T04:38:52 +05:00',
    tags: [
      'qui',
      'est',
      'magna',
      'sit',
      'elit',
      'cupidatat',
      'occaecat',
    ],
  },
};
export default {
  projects,
};
