const projects = {
  1: {
    _id: 'fo596aa7a1bc6d7ea8d90f8d65o',
    index: 0,
    isActive: true,
    important: false,
    url: 'portfolio.kaplan.edu',
    screens: [
      '/static/img/projects/kaplan-portfolio/01-phone.jpg',
      '/static/img/projects/kaplan-portfolio/01-tablet.jpg',
      '/static/img/projects/kaplan-portfolio/01.jpg',
    ],
    pictureHome: '/static/img/projects/kaplan-portfolio/thumb.jpg',
    name: 'Kaplan Portfolio Assessment',
    company: 'Kaplan University',
    project: 'Portfolio Assessment',
    roles: [
      'Ideation',
      'UX Design',
      'Front-end Developemnt',
    ],
    body: 'WebApp for Kaplan University, to help potencial students get college credits for whether user you’ve been working for years, served in the military, or spent time volunteering, showcasing your knowledge through our credit-for-work experience courses could save you thousands of dollars and help you finish your Kaplan University undergraduate degree faster.',
    released: 'November 2013',
    colors: [
      '#232a4d',
      '#434b68',
      '#0198ce',
      '#e0e0e0',
      '#333333',
    ],
    font: {
      face: 'Helvetica Neue',
      local: true,
      url: '',
    },
    stack: {
      1: {
        title: 'SketchApp',
        icon: 'icon-sketch',
      },
      2: {
        title: 'CreativeCloud',
        icon: 'icon-adobe',
      },
      3: {
        title: 'CSS',
        icon: 'icon-css',
      },
      4: {
        title: 'HTML5 Video',
        icon: 'icon-html',
      },
      5: {
        title: 'jQuery',
        icon: 'icon-jquery',
      },
      6: {
        title: 'Git',
        icon: 'icon-git',
      },
      7: {
        title: 'Angular',
        icon: 'icon-angular',
      },
      8: {
        title: 'Gulp',
        icon: 'icon-gulp',
      },
    },
  },
  2: {
    _id: '596aa7a1f1b049709b166c49',
    index: 1,
    isActive: true,
    important: true,
    picture: 'http://placehold.it/1300x400',
    pictureHome: 'http://placehold.it/600x600',
    name: 'Kaplan Portfolio',
    company: 'Kaplan University',
    project: 'Voluptate anim ea ut excepteur laboris ullamco dolore.',
    body: 'Qui sint nulla culpa est occaecat exercitation veniam est Lorem magna dolore ex fugiat. Anim minim nostrud culpa duis officia velit Lorem qui labore sit. Eu sit et et ipsum eiusmod laborum eu magna aute. Eu proident occaecat non do excepteur fugiat veniam culpa adipisicing ipsum reprehenderit tempor.\r\nDolor nostrud elit aute pariatur velit nulla mollit reprehenderit mollit velit dolor sit nostrud labore. Do ea velit eiusmod ad culpa consequat et nostrud. Amet anim labore sit mollit ad cupidatat magna sunt laboris consectetur cupidatat.\r\nVelit Lorem adipisicing labore ipsum dolore dolore sint laborum officia. Eiusmod veniam elit irure voluptate. Anim culpa consequat sint velit cillum mollit excepteur tempor fugiat. Cillum quis et veniam sit Lorem aliqua irure adipisicing ad irure fugiat nostrud fugiat. Occaecat tempor labore velit fugiat eiusmod eu quis nostrud id deserunt sit ad occaecat sint. Ex adipisicing in aute aute non nisi ullamco culpa irure Lorem amet fugiat sunt labore. Duis mollit laborum deserunt consectetur eiusmod aute voluptate cillum mollit irure irure.\r\n',
    released: '2014-08-01T09:36:24 +04:00',
    tags: [
      'irure',
      'voluptate',
      'consequat',
      'exercitation',
      'deserunt',
      'ad',
      'laborum',
    ],
  },
  3: {
    _id: '596aa7a198e0b44c44cf9398',
    index: 2,
    isActive: false,
    important: false,
    picture: 'http://placehold.it/1300x400',
    pictureHome: 'http://placehold.it/600x600',
    name: 'qui dolor sit Lorem dolore',
    company: 'Shadease',
    project: 'Proident veniam qui commodo labore Lorem.',
    body: 'Reprehenderit nulla deserunt cupidatat ipsum velit anim excepteur irure eiusmod ipsum labore sunt. Quis minim consequat aliquip sit amet laboris aliquip voluptate pariatur. Reprehenderit cupidatat elit dolor culpa deserunt. In incididunt amet proident minim amet duis esse. Labore officia fugiat magna adipisicing ut. Excepteur ea duis anim deserunt dolore aliqua sint. Non voluptate in Lorem tempor labore anim sit est.\r\nAdipisicing magna adipisicing nisi adipisicing commodo ea aliqua deserunt. Eiusmod duis sunt et cupidatat nisi dolore excepteur do dolore laboris nostrud esse irure deserunt. Est in qui labore ex amet esse esse eiusmod ullamco occaecat. Ex nisi laboris excepteur culpa. Consequat occaecat eu ullamco mollit ea tempor et et excepteur mollit enim excepteur. Dolore et enim pariatur est laboris officia.\r\nDolore incididunt ad sunt ipsum voluptate aliquip ipsum commodo et do et enim. Elit ad culpa proident exercitation veniam. Nostrud ad duis commodo cupidatat proident reprehenderit dolor aliquip commodo cupidatat incididunt. Sit labore exercitation aliquip incididunt sit sunt et. Sunt eu consequat enim Lorem voluptate veniam. Nostrud cillum id velit ad reprehenderit quis esse.\r\n',
    released: '2015-10-09T11:12:37 +04:00',
    tags: [
      'veniam',
      'voluptate',
      'et',
      'exercitation',
      'tempor',
      'Lorem',
      'labore',
    ],
  },
  4: {
    _id: '596aa7a18f3c981b2c391546',
    index: 3,
    isActive: true,
    important: false,
    picture: 'http://placehold.it/1300x400',
    pictureHome: 'http://placehold.it/600x600',
    name: 'consectetur laborum ullamco dolore excepteur',
    company: 'Biospan',
    project: 'Reprehenderit sint id anim qui non ullamco non.',
    body: 'Velit aute magna sunt officia culpa commodo est. Nisi esse quis aliquip sunt reprehenderit. Nulla sint sit id aute amet occaecat tempor. Duis nisi pariatur Lorem sunt ex voluptate eiusmod est commodo elit tempor. Velit magna culpa labore ipsum ad occaecat qui est dolore fugiat incididunt aliquip. Amet anim reprehenderit consectetur voluptate nulla nulla. Officia culpa elit in excepteur nisi cillum incididunt anim exercitation.\r\nAliqua ad deserunt esse cupidatat sit fugiat cillum minim minim mollit ad. Sint ex magna id elit irure fugiat exercitation adipisicing. Adipisicing exercitation esse nulla proident consectetur id occaecat occaecat qui. Ullamco tempor sint aute quis in. Veniam laborum non consequat anim officia enim ad amet ullamco magna nisi ipsum deserunt duis. Anim enim in pariatur pariatur commodo dolor laborum eu proident eiusmod. Irure ullamco labore quis laboris nulla quis.\r\nNon duis aliquip est aliqua culpa Lorem laboris incididunt excepteur amet irure reprehenderit. Consectetur minim sit consequat laboris esse nisi veniam. Cupidatat sunt eu Lorem sunt. Elit aliquip culpa duis aliqua voluptate anim reprehenderit proident mollit. Consectetur nulla deserunt excepteur reprehenderit tempor magna ullamco non aute eu enim deserunt aliquip. Adipisicing tempor adipisicing officia incididunt aute nulla ullamco eiusmod.\r\n',
    released: '2015-12-01T05:54:49 +05:00',
    tags: [
      'non',
      'do',
      'exercitation',
      'duis',
      'minim',
      'qui',
      'eu',
    ],
  },
  5: {
    _id: '596aa7a1b58714fbe56ec412',
    index: 4,
    isActive: true,
    important: false,
    picture: 'http://placehold.it/1300x400',
    pictureHome: 'http://placehold.it/500x500',
    name: 'id deserunt eu duis ea',
    company: 'Zenolux',
    project: 'Adipisicing laborum proident tempor aliquip irure proident ullamco sit sint.',
    body: 'Cillum fugiat fugiat quis enim voluptate non reprehenderit exercitation ut magna culpa nostrud dolore sunt. In qui tempor quis tempor exercitation velit cillum incididunt aliquip pariatur anim et. Deserunt aliqua elit nulla id ullamco sit.\r\nReprehenderit occaecat deserunt id dolore magna officia Lorem tempor sunt proident cillum. Occaecat dolore nisi non sunt ad cillum irure culpa. Commodo est reprehenderit anim exercitation laboris esse. In ipsum nulla aliqua sit duis Lorem est. Irure ullamco do duis adipisicing consequat cillum cillum aliquip. Velit esse id fugiat aliquip commodo labore. Sint incididunt amet Lorem id.\r\nId nisi non ipsum commodo do esse occaecat. Dolore incididunt est amet sit. Id aliquip dolor nisi exercitation enim ut in incididunt consectetur incididunt ad ea. Occaecat irure velit culpa mollit ullamco consectetur officia. Elit consectetur adipisicing sint occaecat aliqua. Incididunt ea sint consequat dolor laboris tempor labore.\r\n',
    released: '2014-11-12T04:38:52 +05:00',
    tags: [
      'qui',
      'est',
      'magna',
      'sit',
      'elit',
      'cupidatat',
      'occaecat',
    ],
  },
  6: {
    _id: '596aa7a1f1b049709b166c49',
    index: 1,
    isActive: true,
    important: false,
    picture: 'http://placehold.it/1300x400',
    pictureHome: 'http://placehold.it/500x500',
    name: 'elit sit aute est consectetur',
    company: 'Fortean2',
    project: 'Voluptate anim ea ut excepteur laboris ullamco dolore.',
    body: 'Qui sint nulla culpa est occaecat exercitation veniam est Lorem magna dolore ex fugiat. Anim minim nostrud culpa duis officia velit Lorem qui labore sit. Eu sit et et ipsum eiusmod laborum eu magna aute. Eu proident occaecat non do excepteur fugiat veniam culpa adipisicing ipsum reprehenderit tempor.\r\nDolor nostrud elit aute pariatur velit nulla mollit reprehenderit mollit velit dolor sit nostrud labore. Do ea velit eiusmod ad culpa consequat et nostrud. Amet anim labore sit mollit ad cupidatat magna sunt laboris consectetur cupidatat.\r\nVelit Lorem adipisicing labore ipsum dolore dolore sint laborum officia. Eiusmod veniam elit irure voluptate. Anim culpa consequat sint velit cillum mollit excepteur tempor fugiat. Cillum quis et veniam sit Lorem aliqua irure adipisicing ad irure fugiat nostrud fugiat. Occaecat tempor labore velit fugiat eiusmod eu quis nostrud id deserunt sit ad occaecat sint. Ex adipisicing in aute aute non nisi ullamco culpa irure Lorem amet fugiat sunt labore. Duis mollit laborum deserunt consectetur eiusmod aute voluptate cillum mollit irure irure.\r\n',
    released: '2014-08-01T09:36:24 +04:00',
    tags: [
      'irure',
      'voluptate',
      'consequat',
      'exercitation',
      'deserunt',
      'ad',
      'laborum',
    ],
  },
  7: {
    _id: '596aa7a18f3c981b2c391546',
    index: 3,
    isActive: true,
    important: true,
    picture: 'http://placehold.it/1300x400',
    pictureHome: 'http://placehold.it/500x500',
    name: 'consectetur laborum ullamco dolore excepteur',
    company: 'Biospan2',
    project: 'Reprehenderit sint id anim qui non ullamco non.',
    body: 'Velit aute magna sunt officia culpa commodo est. Nisi esse quis aliquip sunt reprehenderit. Nulla sint sit id aute amet occaecat tempor. Duis nisi pariatur Lorem sunt ex voluptate eiusmod est commodo elit tempor. Velit magna culpa labore ipsum ad occaecat qui est dolore fugiat incididunt aliquip. Amet anim reprehenderit consectetur voluptate nulla nulla. Officia culpa elit in excepteur nisi cillum incididunt anim exercitation.\r\nAliqua ad deserunt esse cupidatat sit fugiat cillum minim minim mollit ad. Sint ex magna id elit irure fugiat exercitation adipisicing. Adipisicing exercitation esse nulla proident consectetur id occaecat occaecat qui. Ullamco tempor sint aute quis in. Veniam laborum non consequat anim officia enim ad amet ullamco magna nisi ipsum deserunt duis. Anim enim in pariatur pariatur commodo dolor laborum eu proident eiusmod. Irure ullamco labore quis laboris nulla quis.\r\nNon duis aliquip est aliqua culpa Lorem laboris incididunt excepteur amet irure reprehenderit. Consectetur minim sit consequat laboris esse nisi veniam. Cupidatat sunt eu Lorem sunt. Elit aliquip culpa duis aliqua voluptate anim reprehenderit proident mollit. Consectetur nulla deserunt excepteur reprehenderit tempor magna ullamco non aute eu enim deserunt aliquip. Adipisicing tempor adipisicing officia incididunt aute nulla ullamco eiusmod.\r\n',
    released: '2015-12-01T05:54:49 +05:00',
    tags: [
      'non',
      'do',
      'exercitation',
      'duis',
      'minim',
      'qui',
      'eu',
    ],
  },
  8: {
    _id: '596aa7a1b58714fbe56ec412',
    index: 4,
    isActive: true,
    important: false,
    picture: 'http://placehold.it/1300x400',
    pictureHome: 'http://placehold.it/500x500',
    name: 'id deserunt eu duis ea',
    company: 'Zenolux2',
    project: 'Adipisicing laborum proident tempor aliquip irure proident ullamco sit sint.',
    body: 'Cillum fugiat fugiat quis enim voluptate non reprehenderit exercitation ut magna culpa nostrud dolore sunt. In qui tempor quis tempor exercitation velit cillum incididunt aliquip pariatur anim et. Deserunt aliqua elit nulla id ullamco sit.\r\nReprehenderit occaecat deserunt id dolore magna officia Lorem tempor sunt proident cillum. Occaecat dolore nisi non sunt ad cillum irure culpa. Commodo est reprehenderit anim exercitation laboris esse. In ipsum nulla aliqua sit duis Lorem est. Irure ullamco do duis adipisicing consequat cillum cillum aliquip. Velit esse id fugiat aliquip commodo labore. Sint incididunt amet Lorem id.\r\nId nisi non ipsum commodo do esse occaecat. Dolore incididunt est amet sit. Id aliquip dolor nisi exercitation enim ut in incididunt consectetur incididunt ad ea. Occaecat irure velit culpa mollit ullamco consectetur officia. Elit consectetur adipisicing sint occaecat aliqua. Incididunt ea sint consequat dolor laboris tempor labore.\r\n',
    released: '2014-11-12T04:38:52 +05:00',
    tags: [
      'qui',
      'est',
      'magna',
      'sit',
      'elit',
      'cupidatat',
      'occaecat',
    ],
  },
};
export default {
  projects,
};
