const projects = {
  1: {
    important: false,
    url: 'portfolio.kaplan.edu',
    screens: [
      '/static/img/projects/kaplan-portfolio/01-phone.jpg',
      '/static/img/projects/kaplan-portfolio/01-tablet.jpg',
      '/static/img/projects/kaplan-portfolio/01.jpg',
    ],
    pictureHome: '/static/img/projects/kaplan-portfolio/thumb.jpg',
    name: 'Kaplan Portfolio Assessment',
    company: 'Kaplan University',
    project: 'Portfolio Assessment',
    roles: [
      'Ideation',
      'UX Design',
      'Front-end Developemnt',
    ],
    body: 'WebApp for Kaplan University, to help potencial students get college credits for whether user you’ve been working for years, served in the military, or spent time volunteering, showcasing your knowledge through our credit-for-work experience courses could save you thousands of dollars and help you finish your Kaplan University undergraduate degree faster.',
    released: 'November 2013',
    colors: [
      '#232a4d',
      '#434b68',
      '#0198ce',
      '#e0e0e0',
      '#333333',
    ],
    font: {
      face: 'Helvetica Neue',
      family: '"HelveticaNeue-UltraLight", "Helvetica Neue UltraLight", "Helvetica Neue", Helvetica, sans-serif',
      weight: 100,
      local: true,
      url: '',
    },
    stack: {
      1: {
        title: 'SketchApp',
        icon: 'icon-sketch',
      },
      2: {
        title: 'CreativeCloud',
        icon: 'icon-adobe',
      },
      3: {
        title: 'CSS',
        icon: 'icon-css',
      },
      4: {
        title: 'HTML5 Video',
        icon: 'icon-html',
      },
      5: {
        title: 'jQuery',
        icon: 'icon-jquery',
      },
      6: {
        title: 'Git',
        icon: 'icon-git',
      },
      7: {
        title: 'Angular',
        icon: 'icon-angular',
      },
      8: {
        title: 'Gulp',
        icon: 'icon-gulp',
      },
    },
  },
  2: {
    important: true,
    url: 'private',
    screens: [
      '/static/img/projects/bhi/bhi-lecture-series1.jpg',
      '/static/img/projects/bhi/bhi-lecture-series2.jpg',
    ],
    pictureHome: '/static/img/projects/bhi/thumb.jpg',
    name: 'Brain an Owners Guide',
    company: 'Center for the Brain Health',
    project: 'Brain an Owners Guide',
    roles: [
      'UX Design',
      'Front-end Developemnt',
    ],
    body: 'The Brain lecture series 2015 Center for the Brain Health annual series sell-out public lecture series, delivers groundbreaking brain health research straight from renowned leaders of the field',
    released: 'January 2015',
    colors: [
      '#202c38',
      '#384a5e',
      '#384a5e',
      '#b0d041',
      '#f0752f',
      '#a1539e',
      '#FFFFFF',
    ],
    font: {
      face: 'Helvetica Neue',
      family: '"HelveticaNeue-UltraLight", "Helvetica Neue UltraLight", "Helvetica Neue", Helvetica, sans-serif',
      weight: 200,
      local: true,
      url: '',
    },
    stack: {
      2: {
        title: 'CreativeCloud',
        icon: 'icon-adobe',
      },
      3: {
        title: 'CSS',
        icon: 'icon-css',
      },
      4: {
        title: 'HTML5',
        icon: 'icon-html',
      },
      5: {
        title: 'jQuery',
        icon: 'icon-jquery',
      },
      6: {
        title: 'Git',
        icon: 'icon-git',
      },
    },
  },
  3: {
    important: false,
    url: 'visionaryvoices.kaplan.edu',
    screens: [
      '/static/img/projects/vv/home.jpg',
      '/static/img/projects/vv/categories.jpg',
      '/static/img/projects/vv/event.jpg',
      '/static/img/projects/vv/categories-ui.jpg',
      '/static/img/projects/vv/speakers.jpg',
      '/static/img/projects/vv/home-ipad-nav.jpg',
    ],
    pictureHome: '/static/img/projects/vv/thumb.jpg',
    name: 'Kaplan Visionary Voices',
    company: 'Kaplan Inc.',
    project: 'Visionary Voices',
    roles: [
      'UX Design',
      'Front-end Developemnt',
    ],
    body: 'Kaplan University presents Visionary Voices, a series of interviews that chronicle our goals in regards to adult education and continuing education throughout your life. Kaplan University offers online degree programs designed to expand the way you think and help you develop both personally and professionally. Students turn to us to develop their critical thinking skills, to challenge and prepare them for successful careers.',
    released: 'February 2014',
    colors: [
      '#2e2f33',
      '#444444',
      '#00a6da',
      '#dfdfdf',
      '#000000',
    ],
    font: {
      face: 'Open Sans',
      family: '"Open Sans", sans-serif',
      weight: 200,
      local: false,
      url: 'https://fonts.googleapis.com/css?family=Open+Sans:300',
    },
    stack: {
      1: {
        title: 'CreativeCloud',
        icon: 'icon-adobe',
      },
      2: {
        title: 'CSS',
        icon: 'icon-css',
      },
      3: {
        title: 'HTML5',
        icon: 'icon-html',
      },
      4: {
        title: 'jQuery',
        icon: 'icon-jquery',
      },
      5: {
        title: 'Git',
        icon: 'icon-git',
      },
    },
  },
  4: {
    _id: '596aa7a18f3c981b2c391546',
    index: 3,
    isActive: true,
    important: false,
    picture: 'http://placehold.it/1300x400',
    pictureHome: 'http://placehold.it/600x600',
    name: 'consectetur laborum ullamco dolore excepteur',
    company: 'Biospan',
    project: 'Reprehenderit sint id anim qui non ullamco non.',
    body: 'Velit aute magna sunt officia culpa commodo est. Nisi esse quis aliquip sunt reprehenderit. Nulla sint sit id aute amet occaecat tempor. Duis nisi pariatur Lorem sunt ex voluptate eiusmod est commodo elit tempor. Velit magna culpa labore ipsum ad occaecat qui est dolore fugiat incididunt aliquip. Amet anim reprehenderit consectetur voluptate nulla nulla. Officia culpa elit in excepteur nisi cillum incididunt anim exercitation.\r\nAliqua ad deserunt esse cupidatat sit fugiat cillum minim minim mollit ad. Sint ex magna id elit irure fugiat exercitation adipisicing. Adipisicing exercitation esse nulla proident consectetur id occaecat occaecat qui. Ullamco tempor sint aute quis in. Veniam laborum non consequat anim officia enim ad amet ullamco magna nisi ipsum deserunt duis. Anim enim in pariatur pariatur commodo dolor laborum eu proident eiusmod. Irure ullamco labore quis laboris nulla quis.\r\nNon duis aliquip est aliqua culpa Lorem laboris incididunt excepteur amet irure reprehenderit. Consectetur minim sit consequat laboris esse nisi veniam. Cupidatat sunt eu Lorem sunt. Elit aliquip culpa duis aliqua voluptate anim reprehenderit proident mollit. Consectetur nulla deserunt excepteur reprehenderit tempor magna ullamco non aute eu enim deserunt aliquip. Adipisicing tempor adipisicing officia incididunt aute nulla ullamco eiusmod.\r\n',
    released: '2015-12-01T05:54:49 +05:00',
    tags: [
      'non',
      'do',
      'exercitation',
      'duis',
      'minim',
      'qui',
      'eu',
    ],
  },
  5: {
    _id: '596aa7a1b58714fbe56ec412',
    index: 4,
    isActive: true,
    important: false,
    picture: 'http://placehold.it/1300x400',
    pictureHome: 'http://placehold.it/500x500',
    name: 'id deserunt eu duis ea',
    company: 'Zenolux',
    project: 'Adipisicing laborum proident tempor aliquip irure proident ullamco sit sint.',
    body: 'Cillum fugiat fugiat quis enim voluptate non reprehenderit exercitation ut magna culpa nostrud dolore sunt. In qui tempor quis tempor exercitation velit cillum incididunt aliquip pariatur anim et. Deserunt aliqua elit nulla id ullamco sit.\r\nReprehenderit occaecat deserunt id dolore magna officia Lorem tempor sunt proident cillum. Occaecat dolore nisi non sunt ad cillum irure culpa. Commodo est reprehenderit anim exercitation laboris esse. In ipsum nulla aliqua sit duis Lorem est. Irure ullamco do duis adipisicing consequat cillum cillum aliquip. Velit esse id fugiat aliquip commodo labore. Sint incididunt amet Lorem id.\r\nId nisi non ipsum commodo do esse occaecat. Dolore incididunt est amet sit. Id aliquip dolor nisi exercitation enim ut in incididunt consectetur incididunt ad ea. Occaecat irure velit culpa mollit ullamco consectetur officia. Elit consectetur adipisicing sint occaecat aliqua. Incididunt ea sint consequat dolor laboris tempor labore.\r\n',
    released: '2014-11-12T04:38:52 +05:00',
    tags: [
      'qui',
      'est',
      'magna',
      'sit',
      'elit',
      'cupidatat',
      'occaecat',
    ],
  },
  6: {
    _id: '596aa7a1f1b049709b166c49',
    index: 1,
    isActive: true,
    important: false,
    picture: 'http://placehold.it/1300x400',
    pictureHome: 'http://placehold.it/500x500',
    name: 'elit sit aute est consectetur',
    company: 'Fortean2',
    project: 'Voluptate anim ea ut excepteur laboris ullamco dolore.',
    body: 'Qui sint nulla culpa est occaecat exercitation veniam est Lorem magna dolore ex fugiat. Anim minim nostrud culpa duis officia velit Lorem qui labore sit. Eu sit et et ipsum eiusmod laborum eu magna aute. Eu proident occaecat non do excepteur fugiat veniam culpa adipisicing ipsum reprehenderit tempor.\r\nDolor nostrud elit aute pariatur velit nulla mollit reprehenderit mollit velit dolor sit nostrud labore. Do ea velit eiusmod ad culpa consequat et nostrud. Amet anim labore sit mollit ad cupidatat magna sunt laboris consectetur cupidatat.\r\nVelit Lorem adipisicing labore ipsum dolore dolore sint laborum officia. Eiusmod veniam elit irure voluptate. Anim culpa consequat sint velit cillum mollit excepteur tempor fugiat. Cillum quis et veniam sit Lorem aliqua irure adipisicing ad irure fugiat nostrud fugiat. Occaecat tempor labore velit fugiat eiusmod eu quis nostrud id deserunt sit ad occaecat sint. Ex adipisicing in aute aute non nisi ullamco culpa irure Lorem amet fugiat sunt labore. Duis mollit laborum deserunt consectetur eiusmod aute voluptate cillum mollit irure irure.\r\n',
    released: '2014-08-01T09:36:24 +04:00',
    tags: [
      'irure',
      'voluptate',
      'consequat',
      'exercitation',
      'deserunt',
      'ad',
      'laborum',
    ],
  },
  7: {
    _id: '596aa7a18f3c981b2c391546',
    index: 3,
    isActive: true,
    important: true,
    picture: 'http://placehold.it/1300x400',
    pictureHome: 'http://placehold.it/500x500',
    name: 'consectetur laborum ullamco dolore excepteur',
    company: 'Biospan2',
    project: 'Reprehenderit sint id anim qui non ullamco non.',
    body: 'Velit aute magna sunt officia culpa commodo est. Nisi esse quis aliquip sunt reprehenderit. Nulla sint sit id aute amet occaecat tempor. Duis nisi pariatur Lorem sunt ex voluptate eiusmod est commodo elit tempor. Velit magna culpa labore ipsum ad occaecat qui est dolore fugiat incididunt aliquip. Amet anim reprehenderit consectetur voluptate nulla nulla. Officia culpa elit in excepteur nisi cillum incididunt anim exercitation.\r\nAliqua ad deserunt esse cupidatat sit fugiat cillum minim minim mollit ad. Sint ex magna id elit irure fugiat exercitation adipisicing. Adipisicing exercitation esse nulla proident consectetur id occaecat occaecat qui. Ullamco tempor sint aute quis in. Veniam laborum non consequat anim officia enim ad amet ullamco magna nisi ipsum deserunt duis. Anim enim in pariatur pariatur commodo dolor laborum eu proident eiusmod. Irure ullamco labore quis laboris nulla quis.\r\nNon duis aliquip est aliqua culpa Lorem laboris incididunt excepteur amet irure reprehenderit. Consectetur minim sit consequat laboris esse nisi veniam. Cupidatat sunt eu Lorem sunt. Elit aliquip culpa duis aliqua voluptate anim reprehenderit proident mollit. Consectetur nulla deserunt excepteur reprehenderit tempor magna ullamco non aute eu enim deserunt aliquip. Adipisicing tempor adipisicing officia incididunt aute nulla ullamco eiusmod.\r\n',
    released: '2015-12-01T05:54:49 +05:00',
    tags: [
      'non',
      'do',
      'exercitation',
      'duis',
      'minim',
      'qui',
      'eu',
    ],
  },
  8: {
    _id: '596aa7a1b58714fbe56ec412',
    index: 4,
    isActive: true,
    important: false,
    picture: 'http://placehold.it/1300x400',
    pictureHome: 'http://placehold.it/500x500',
    name: 'id deserunt eu duis ea',
    company: 'Zenolux2',
    project: 'Adipisicing laborum proident tempor aliquip irure proident ullamco sit sint.',
    body: 'Cillum fugiat fugiat quis enim voluptate non reprehenderit exercitation ut magna culpa nostrud dolore sunt. In qui tempor quis tempor exercitation velit cillum incididunt aliquip pariatur anim et. Deserunt aliqua elit nulla id ullamco sit.\r\nReprehenderit occaecat deserunt id dolore magna officia Lorem tempor sunt proident cillum. Occaecat dolore nisi non sunt ad cillum irure culpa. Commodo est reprehenderit anim exercitation laboris esse. In ipsum nulla aliqua sit duis Lorem est. Irure ullamco do duis adipisicing consequat cillum cillum aliquip. Velit esse id fugiat aliquip commodo labore. Sint incididunt amet Lorem id.\r\nId nisi non ipsum commodo do esse occaecat. Dolore incididunt est amet sit. Id aliquip dolor nisi exercitation enim ut in incididunt consectetur incididunt ad ea. Occaecat irure velit culpa mollit ullamco consectetur officia. Elit consectetur adipisicing sint occaecat aliqua. Incididunt ea sint consequat dolor laboris tempor labore.\r\n',
    released: '2014-11-12T04:38:52 +05:00',
    tags: [
      'qui',
      'est',
      'magna',
      'sit',
      'elit',
      'cupidatat',
      'occaecat',
    ],
  },
};
export default {
  projects,
};
